"""Constants for the portfolio scraper application."""

# Environment variable keys
LLM_PROVIDER_KEY = "LLM_PROVIDER"
ANTHROPIC_MODEL_KEY = "ANTHROPIC_MODEL"
ANTHROPIC_PLANNER_MODEL_KEY = "ANTHROPIC_PLANNER_MODEL"
OLLAMA_MODEL_KEY = "OLLAMA_MODEL"
OLLAMA_PLANNER_MODEL_KEY = "OLLAMA_PLANNER_MODEL"
OLLAMA_NUM_CTX_KEY = "OLLAMA_NUM_CTX"
GEMINI_MODEL_KEY = "GEMINI_MODEL"
GEMINI_PLANNER_MODEL_KEY = "GEMINI_PLANNER_MODEL"
GEMINI_API_KEY = "GEMINI_API_KEY"
OPENAI_MODEL_KEY = "OPENAI_MODEL"
OPENAI_PLANNER_MODEL_KEY = "OPENAI_PLANNER_MODEL"
PORTFOLIO_URL_KEY = "PORTFOLIO_URL"
BROWSER_HEADLESS_KEY = "BROWSER_HEADLESS"
INFLUX_URL_KEY = "INFLUX_URL"
INFLUX_TOKEN_KEY = "INFLUX_TOKEN"
INFLUX_ORG_KEY = "INFLUX_ORG"
INFLUX_BUCKET_KEY = "INFLUX_BUCKET"
PLANNER_REASONING_KEY = "PLANNER_REASONING"

# Chrome debug settings
CHROME_DEBUG_PORT = 9222
CHROME_DEBUG_URL = f"http://localhost:{CHROME_DEBUG_PORT}"

# Default model values
DEFAULT_OPENAI_MODEL = "gpt-4.1-mini-2025-04-14"
DEFAULT_OPENAI_PLANNER_MODEL = "gpt-4.1-2025-04-14"
DEFAULT_ANTHROPIC_MODEL = "claude-3-5-sonnet-20240620"
DEFAULT_OLLAMA_MODEL = "llama3.2:3b"
DEFAULT_OLLAMA_NUM_CTX = "32000"
DEFAULT_GEMINI_MODEL = "gemini-2.0-flash-exp"

# Browser config defaults
DEFAULT_MIN_WAIT_PAGE_LOAD_TIME = 2
DEFAULT_WAIT_FOR_NETWORK_IDLE_PAGE_LOAD_TIME = 4
